name: quickfix
description: "Application QuickFix"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_lints: ^2.0.0
  # multidex: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
